services:
- name: diamond.service
- name: image-cleaner.service
  version: 1.0.0
- name: neo4j-hot-backup@.service
  version: 1.1-go
  count: 1
  desiredState: loaded
- name: neo4j-hot-backup@.timer
  count: 1
- name: neo4j-logger@.service
  count: 3
- name: splunk-forwarder.service
- name: tunnel-registrator.service
  version: v1.0.3
- name: neo4j-sidekick@.service
  count: 3
- name: neo4j@.service
  version: 3.1.0-enterprise
  count: 3
  sequentialDeployment: true
- name: alb-dns-registrator.service
  version: v1.0.0
- name: collectd-cloudwatch-container.service
  version: v2.0.5
