services:
- name: diamond.service
- name: image-cleaner.service
  version: 1.0.0
- name: neo4j-logger@.service
  count: 1
- name: splunk-forwarder.service
- name: tunnel-registrator.service
  version: v1.0.3
- name: neo4j-read-replica@.service
  version: 3.2.2-enterprise
  count: 1
  sequentialDeployment: true
- name: alb-dns-registrator.service
  version: v1.0.0
- name: collectd-cloudwatch-container.service
  version: v2.0.12