services:
- name: diamond.service
- name: image-cleaner.service
  version: 1.0.0
- name: neo4j-hot-backup@.service
  version: 1.1-go
  count: 1
  desiredState: loaded
- name: neo4j-hot-backup@.timer
  count: 1
- name: splunk-forwarder.service
- name: tunnel-registrator.service
  version: v1.0.3
